login_body = """<?xml version="1.0" encoding="utf-8" ?>
    <env:Envelope
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
        <env:Body>
            <n1:login xmlns:n1="urn:partner.soap.sforce.com">
                <n1:username>{username}</n1:username>
                <n1:password>{password}</n1:password>
            </n1:login>
        </env:Body>
    </env:Envelope>"""

execute_anonymous_body = """
    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
    xmlns:apex="http://soap.sforce.com/2006/08/apex">
       <soapenv:Header>
          <apex:DebuggingHeader>
             <apex:debugLevel>Detail</apex:debugLevel>
          </apex:DebuggingHeader>
          <apex:SessionHeader>
            <sessionId>{session_id}</sessionId>
          </apex:SessionHeader>
       </soapenv:Header>
       <soapenv:Body>
          <apex:executeAnonymous>
             <apex:String>{apex_string}</apex:String>
          </apex:executeAnonymous>
       </soapenv:Body>
    </soapenv:Envelope>"""

describe_layout_body = """
    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
        xmlns:urn="urn:partner.soap.sforce.com">
        <soapenv:Header>
            <urn:SessionHeader>
                <urn:sessionId>{session_id}</urn:sessionId>
            </urn:SessionHeader>
        </soapenv:Header>
        <soapenv:Body>
            <urn:describeLayout>
                <urn:sObjectType>{sobject}</urn:sObjectType>
                <urn:recordTypeIds>{recordtype_id}</urn:recordTypeIds>
            </urn:describeLayout>
        </soapenv:Body>
    </soapenv:Envelope>"""

check_status_body = """
  <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
  xmlns:met="http://soap.sforce.com/2006/04/metadata">
     <soapenv:Header>
        <met:SessionHeader>
           <met:sessionId>{session_id}</met:sessionId>
        </met:SessionHeader>
     </soapenv:Header>
     <soapenv:Body>
        <met:checkStatus>
           <met:asyncProcessId>{async_process_id}</met:asyncProcessId>
        </met:checkStatus>
     </soapenv:Body>
  </soapenv:Envelope>
  """

check_retrieve_status_body = """
  <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
  xmlns:met="http://soap.sforce.com/2006/04/metadata">
     <soapenv:Header>
        <met:SessionHeader>
           <met:sessionId>{session_id}</met:sessionId>
        </met:SessionHeader>
     </soapenv:Header>
     <soapenv:Body>
        <met:checkRetrieveStatus>
           <met:asyncProcessId>{async_process_id}</met:asyncProcessId>
        </met:checkRetrieveStatus>
     </soapenv:Body>
  </soapenv:Envelope>
  """

retrieve_sobjects_workflow_task_body = """
  <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
  xmlns:met="http://soap.sforce.com/2006/04/metadata">
     <soapenv:Header>
        <met:SessionHeader>
           <met:sessionId>{session_id}</met:sessionId>
        </met:SessionHeader>
     </soapenv:Header>
     <soapenv:Body>
        <met:retrieve>
           <met:retrieveRequest>
              <met:apiVersion>28.0</met:apiVersion>
              <met:unpackaged>
                  <met:types>
                      <met:members>*</met:members>
                      <met:members>Account</met:members>
                      <met:members>AccountContactRole</met:members>
                      <met:members>Activity</met:members>
                      <met:members>Asset</met:members>
                      <met:members>Campaign</met:members>
                      <met:members>CampaignMember</met:members>
                      <met:members>Case</met:members>
                      <met:members>CaseContactRole</met:members>
                      <met:members>Contact</met:members>
                      <met:members>ContentVersion</met:members>
                      <met:members>Contract</met:members>
                      <met:members>ContractContactRole</met:members>
                      <met:members>Event</met:members>
                      <met:members>Idea</met:members>
                      <met:members>Lead</met:members>
                      <met:members>Opportunity</met:members>
                      <met:members>OpportunityContactRole</met:members>
                      <met:members>OpportunityLineItem</met:members>
                      <met:members>PartnerRole</met:members>
                      <met:members>Product2</met:members>
                      <met:members>Question</met:members>
                      <met:members>Reply</met:members>
                      <met:members>Site</met:members>
                      <met:members>SnapshotAuditEvent</met:members>
                      <met:members>SnapshotBin</met:members>
                      <met:members>SnapshotConfig</met:members>
                      <met:members>Solution</met:members>
                      <met:members>Task</met:members>
                      <met:members>User</met:members>
                      <met:members>UserLicense</met:members>
                      <name>CustomObject</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>Workflow</name>
                  </met:types>
                  <met:version>28.0</met:version>
              </met:unpackaged>
           </met:retrieveRequest>
        </met:retrieve>
     </soapenv:Body>
  </soapenv:Envelope>"""

retrieve_all_task_body = """
  <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
  xmlns:met="http://soap.sforce.com/2006/04/metadata">
     <soapenv:Header>
        <met:SessionHeader>
           <met:sessionId>{session_id}</met:sessionId>
        </met:SessionHeader>
     </soapenv:Header>
     <soapenv:Body>
        <met:retrieve>
           <met:retrieveRequest>
              <met:apiVersion>28.0</met:apiVersion>
              <met:unpackaged>
                  <met:types>
                    <met:members>*</met:members>
                    <name>AnalyticSnapshot</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>ApexClass</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>ApexComponent</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>ApexPage</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>ApexTrigger</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>CustomApplication</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>CustomLabels</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <met:members>Account</met:members>
                      <met:members>AccountContactRole</met:members>
                      <met:members>Activity</met:members>
                      <met:members>Asset</met:members>
                      <met:members>Campaign</met:members>
                      <met:members>CampaignMember</met:members>
                      <met:members>Case</met:members>
                      <met:members>CaseContactRole</met:members>
                      <met:members>Contact</met:members>
                      <met:members>ContentVersion</met:members>
                      <met:members>Contract</met:members>
                      <met:members>ContractContactRole</met:members>
                      <met:members>Event</met:members>
                      <met:members>Idea</met:members>
                      <met:members>Lead</met:members>
                      <met:members>Opportunity</met:members>
                      <met:members>OpportunityContactRole</met:members>
                      <met:members>OpportunityLineItem</met:members>
                      <met:members>PartnerRole</met:members>
                      <met:members>Product2</met:members>
                      <met:members>Question</met:members>
                      <met:members>Reply</met:members>
                      <met:members>Site</met:members>
                      <met:members>SnapshotAuditEvent</met:members>
                      <met:members>SnapshotBin</met:members>
                      <met:members>SnapshotConfig</met:members>
                      <met:members>Solution</met:members>
                      <met:members>Task</met:members>
                      <met:members>User</met:members>
                      <met:members>UserLicense</met:members>
                      <name>CustomObject</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>CustomObjectTranslation</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>CustomPageWebLink</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>CustomSite</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>CustomTab</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>Dashboard</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>DataCategoryGroup</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>Document</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>EmailTemplate</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>HomePageComponent</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>HomePageLayout</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>Layout</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>Letterhead</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>Profile</name>
                  </met:types>
                  <met:types>
                      <met:members>WebMethod</met:members>
                      <met:members>ePOP_Service</met:members>
                      <name>RemoteSiteSetting</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>Report</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>ReportType</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>Scontrol</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>StaticResource</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>Translations</name>
                  </met:types>
                  <met:types>
                      <met:members>*</met:members>
                      <name>Workflow</name>
                  </met:types>
                  <met:version>28.0</met:version>
              </met:unpackaged>
           </met:retrieveRequest>
        </met:retrieve>
     </soapenv:Body>
  </soapenv:Envelope>"""