HTML_ELEMENTS_ATTRIBUTES = {
    '!DOCTYPE' : [],
    'a' : ['accesskey',
        'charset',
        'class',
        'contenteditable',
        'coords',
        'datafld',
        'datasrc',
        'dir',
        'disabled',
        'hidefocus',
        'href',
        'hreflang',
        'id',
        'lang',
        'language',
        'methods',
        'name',
        'rel',
        'rev',
        'shape',
        'style',
        'tabindex',
        'target',
        'title',
        'type',
        'unselectable',
        'urn'],
    'abbr' : ['class', 'dir', 'id', 'lang', 'style', 'title'],
    'acronym' : ['class', 'dir', 'id', 'lang', 'style', 'title'],
    'address' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'applet' : ['accesskey',
        'align',
        'alt',
        'archive',
        'class',
        'code',
        'codebase',
        'datafld',
        'datasrc',
        'height',
        'hidefocus',
        'hspace',
        'id',
        'mayscript',
        'name',
        'object',
        'src',
        'style',
        'tabindex',
        'title',
        'unselectable',
        'vspace',
        'width'],
    'area' : ['accesskey',
        'alt',
        'class',
        'coords',
        'dir',
        'hidefocus',
        'href',
        'id',
        'lang',
        'nohref',
        'shape',
        'style',
        'tabindex',
        'target',
        'title',
        'unselectable'],
    'article' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'aside' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'audio' : ['accesskey',
        'autoplay',
        'class',
        'contenteditable',
        'contextmenu',
        'controls',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'loop',
        'preload',
        'spellcheck',
        'src',
        'style',
        'tabindex',
        'title'],
    'b' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'base' : ['href', 'id', 'target'],
    'basefont' : ['color', 'face', 'id', 'size'],
    'bdo' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'bgsound' : ['balance', 'id', 'loop', 'src', 'volume'],
    'big' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'blink' : ['class', 'id', 'lang', 'style'],
    'blockquote' : ['accesskey',
        'cite',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'body' : ['accesskey',
        'alink',
        'background',
        'bgcolor',
        'bgproperties',
        'bottommargin',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'leftmargin',
        'link',
        'marginheight',
        'marginwidth',
        'nowrap',
        'rightmargin',
        'scroll',
        'style',
        'tabindex',
        'text',
        'title',
        'unselectable',
        'vlink'],
    'br' : ['class', 'clear', 'id', 'style', 'title'],
    'button' : ['accesskey',
        'class',
        'contenteditable',
        'datafld',
        'dataformatas',
        'datasrc',
        'hidefocus',
        'id',
        'lang',
        'language',
        'name',
        'style',
        'tabindex',
        'title',
        'type',
        'value'],
    'canvas' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'height',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title',
        'width'],
    'caption' : ['accesskey',
        'align',
        'class',
        'contenteditable',
        'dir',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable',
        'valign'],
    'center' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'cite' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'code' : ['class',
        'contenteditable',
        'dir',
        'disabled',
        'id',
        'lang',
        'language',
        'style',
        'title',
        'unselectable'],
    'col' : ['align',
        'bgcolor',
        'char',
        'charoff',
        'class',
        'dir',
        'id',
        'lang',
        'span',
        'style',
        'title',
        'valign',
        'width'],
    'colgroup' : ['align',
        'bgcolor',
        'char',
        'charoff',
        'class',
        'dir',
        'id',
        'lang',
        'span',
        'style',
        'title',
        'valign',
        'width'],
    'command' : ['accesskey',
        'checked',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'disabled',
        'draggable',
        'height',
        'hidden',
        'icon',
        'id',
        'label',
        'lang',
        'radiogroup',
        'spellcheck',
        'style',
        'tabindex',
        'title',
        'type',
        'width'],
    'comment' : ['data', 'id', 'lang', 'title'],
    'datalist' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'dd' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'nowrap',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'del' : ['accesskey',
        'cite',
        'class',
        'contenteditable',
        'datetime',
        'dir',
        'disabled',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'details' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'open',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'dfn' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'dir' : ['accesskey',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'language',
        'tabindex',
        'unselectable'],
    'div' : ['accesskey',
        'align',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'nowrap',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'dl' : ['accesskey',
        'class',
        'compact',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'dt' : ['accesskey',
        'class',
        'compact',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'nowrap',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'em' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'embed' : ['accesskey',
        'align',
        'alt',
        'border',
        'class',
        'code',
        'codebase',
        'height',
        'hidden',
        'hspace',
        'id',
        'language',
        'name',
        'palette',
        'pluginspage',
        'src',
        'style',
        'title',
        'type',
        'units',
        'unselectable',
        'vspace',
        'width'],
    'fieldset' : ['accesskey',
        'align',
        'class',
        'contenteditable',
        'datafld',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'figcaption' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'figure' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'font' : ['accesskey',
        'class',
        'color',
        'contenteditable',
        'dir',
        'disabled',
        'face',
        'hidefocus',
        'id',
        'lang',
        'language',
        'point-size',
        'size',
        'style',
        'tabindex',
        'title',
        'unselectable',
        'weight'],
    'footer' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'form' : ['accept-charset',
        'action',
        'autocomplete',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'enctype',
        'hidefocus',
        'id',
        'lang',
        'language',
        'method',
        'name',
        'style',
        'tabindex',
        'target',
        'title',
        'unselectable'],
    'frame' : ['allowtransparency',
        'application',
        'bordercolor',
        'class',
        'datafld',
        'datasrc',
        'frameborder',
        'height',
        'hidefocus',
        'id',
        'lang',
        'language',
        'longdesc',
        'marginheight',
        'marginwidth',
        'name',
        'noresize',
        'scrolling',
        'security',
        'style',
        'tabindex',
        'title',
        'unselectable',
        'width'],
    'frameset' : ['border',
        'bordercolor',
        'class',
        'cols',
        'frameborder',
        'framespacing',
        'hidefocus',
        'id',
        'lang',
        'language',
        'longdesc',
        'rows',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'h1' : ['accesskey',
        'align',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'h2' : ['accesskey',
        'align',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'h3' : ['accesskey',
        'align',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'h4' : ['accesskey',
        'align',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'h5' : ['accesskey',
        'align',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'h6' : ['accesskey',
        'align',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'head' : ['class', 'dir', 'id', 'lang', 'profile'],
    'header' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'hgroup' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'hr' : ['accesskey',
        'align',
        'class',
        'dir',
        'hidefocus',
        'id',
        'lang',
        'language',
        'noshade',
        'size',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'html' : ['class', 'dir', 'id', 'lang', 'scroll', 'xmlns'],
    'i' : ['accesskey',
        'class',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'iframe' : ['align',
        'allowtransparency',
        'application',
        'bordercolor',
        'class',
        'datafld',
        'datasrc',
        'frameborder',
        'height',
        'hidefocus',
        'hspace',
        'id',
        'lang',
        'language',
        'longdesc',
        'marginheight',
        'marginwidth',
        'name',
        'scrolling',
        'security',
        'src',
        'style',
        'tabindex',
        'title',
        'unselectable',
        'vspace',
        'width'],
    'ilayer' : ['above',
        'background',
        'below',
        'class',
        'clip',
        'height',
        'id',
        'left',
        'name',
        'pagex',
        'pagey',
        'src',
        'style',
        'top',
        'visibility',
        'width',
        'z-index'],
    'img' : ['accesskey',
        'align',
        'alt',
        'border',
        'class',
        'datafld',
        'datasrc',
        'dir',
        'dynsrc',
        'galleryimg',
        'height',
        'hidefocus',
        'hspace',
        'id',
        'ismap',
        'lang',
        'language',
        'longdesc',
        'loop',
        'lowsrc',
        'src',
        'style',
        'tabindex',
        'title',
        'unselectable',
        'usemap',
        'vspace',
        'width'],
    'input' : ['accept',
        'accesskey',
        'align',
        'alt',
        'autocomplete',
        'checked',
        'class',
        'dir',
        'disabled',
        'dynsrc',
        'hidefocus',
        'hspace',
        'id',
        'lang',
        'language',
        'loop',
        'lowsrc',
        'maxlength',
        'name',
        'readonly',
        'size',
        'src',
        'style',
        'tabindex',
        'title',
        'type',
        'unselectable',
        'value',
        'vspace'],
    'ins' : ['accesskey',
        'cite',
        'class',
        'contenteditable',
        'datetime',
        'dir',
        'disabled',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'isindex' : ['accesskey',
        'action',
        'class',
        'dir',
        'disabled',
        'hidefocus',
        'href',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'kbd' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'keygen' : ['accesskey',
        'autofocus',
        'challenge',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'disabled',
        'draggable',
        'form',
        'hidden',
        'id',
        'keytype',
        'lang',
        'name',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'label' : ['accesskey',
        'class',
        'contenteditable',
        'datafld',
        'dataformatas',
        'datasrc',
        'dir',
        'disabled',
        'for',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'layer' : ['above',
        'background',
        'below',
        'bgcolor',
        'class',
        'clip',
        'height',
        'id',
        'left',
        'name',
        'overflow',
        'pagex',
        'pagey',
        'style',
        'title',
        'top',
        'visibility',
        'width',
        'z-index'],
    'legend' : ['accesskey',
        'align',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'li' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'type',
        'unselectable',
        'value'],
    'link' : ['charset',
        'class',
        'dir',
        'disabled',
        'href',
        'hreflang',
        'id',
        'lang',
        'media',
        'rel',
        'rev',
        'style',
        'target',
        'title',
        'type'],
    'map' : ['class', 'dir', 'id', 'lang', 'style', 'title'],
    'mark' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'marquee' : ['accesskey',
        'behavior',
        'bgcolor',
        'class',
        'contenteditable',
        'datafld',
        'dataformatas',
        'datasrc',
        'dir',
        'direction',
        'height',
        'hidefocus',
        'hspace',
        'id',
        'lang',
        'language',
        'loop',
        'scrollamount',
        'scrolldelay',
        'style',
        'tabindex',
        'title',
        'truespeed',
        'unselectable',
        'vspace',
        'width'],
    'math' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'menu' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'label',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title',
        'type'],
    'meta' : ['content', 'dir', 'http-equiv', 'id', 'lang', 'name', 'scheme'],
    'meter' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'form',
        'hidden',
        'high',
        'id',
        'label',
        'lang',
        'low',
        'max',
        'min',
        'optimum',
        'spellcheck',
        'style',
        'tabindex',
        'title',
        'type',
        'value'],
    'nav' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'nobr' : ['class',
        'contenteditable',
        'dir',
        'disabled',
        'id',
        'style',
        'title',
        'unselectable'],
    'noembed' : ['class', 'id', 'style', 'title'],
    'noframes' : ['class', 'dir', 'id', 'lang', 'style', 'title'],
    'noscript' : ['class', 'dir', 'id', 'lang', 'style', 'title'],
    'object' : ['accesskey',
        'align',
        'archive',
        'border',
        'class',
        'classid',
        'code',
        'codebase',
        'codetype',
        'data',
        'datafld',
        'datasrc',
        'declare',
        'dir',
        'height',
        'hidefocus',
        'hspace',
        'id',
        'lang',
        'name',
        'standby',
        'style',
        'tabindex',
        'title',
        'type',
        'unselectable',
        'usemap',
        'vspace',
        'width'],
    'ol' : ['accesskey',
        'class',
        'compact',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'reversed',
        'start',
        'style',
        'tabindex',
        'title',
        'type',
        'unselectable'],
    'optgroup' : ['class',
        'dir',
        'disabled',
        'id',
        'label',
        'lang',
        'style',
        'title'],
    'option' : ['class',
        'dir',
        'disabled',
        'id',
        'label',
        'lang',
        'language',
        'selected',
        'style',
        'title',
        'value'],
    'output' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'for',
        'form',
        'hidden',
        'id',
        'lang',
        'name',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'p' : ['accesskey',
        'align',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'param' : ['datafld',
        'dataformatas',
        'datasrc',
        'id',
        'name',
        'type',
        'value',
        'valuetype'],
    'pre' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable',
        'width',
        'wrap',
        'xml:space'],
    'progress' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'form',
        'hidden',
        'id',
        'lang',
        'max',
        'spellcheck',
        'style',
        'tabindex',
        'title',
        'value'],
    'q' : ['accesskey',
        'cite',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'rp' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'rt' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'name',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'ruby' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'name',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    's' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'samp' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'script' : ['charset',
        'defer',
        'event',
        'for',
        'id',
        'language',
        'src',
        'type',
        'xml:space'],
    'section' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'select' : ['accesskey',
        'align',
        'class',
        'datafld',
        'datasrc',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'multiple',
        'name',
        'size',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'small' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'source' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'media',
        'spellcheck',
        'src',
        'style',
        'tabindex',
        'title',
        'type'],
    'span' : ['accesskey',
        'class',
        'contenteditable',
        'datafld',
        'dataformatas',
        'datasrc',
        'dir',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'strike' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'strong' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'style' : ['dir',
        'disabled',
        'id',
        'lang',
        'media',
        'title',
        'type',
        'xml:space'],
    'sub' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'summary' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'sup' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'svg' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'table' : ['accesskey',
        'background',
        'bgcolor',
        'border',
        'bordercolor',
        'bordercolordark',
        'bordercolorlight',
        'cellpadding',
        'cellspacing',
        'class',
        'cols',
        'datapagesize',
        'datasrc',
        'dir',
        'frame',
        'height',
        'hidefocus',
        'hspace',
        'id',
        'lang',
        'language',
        'rules',
        'style',
        'summary',
        'tabindex',
        'title',
        'unselectable',
        'vspace',
        'width'],
    'tbody' : ['accesskey',
        'align',
        'bgcolor',
        'char',
        'charoff',
        'class',
        'dir',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable',
        'valign'],
    'td' : ['abbr',
        'accesskey',
        'align',
        'axis',
        'background',
        'bgcolor',
        'bordercolor',
        'bordercolordark',
        'bordercolorlight',
        'char',
        'charoff',
        'class',
        'colspan',
        'dir',
        'headers',
        'height',
        'hidefocus',
        'id',
        'lang',
        'language',
        'nowrap',
        'rowspan',
        'scope',
        'style',
        'tabindex',
        'title',
        'unselectable',
        'valign',
        'width'],
    'textarea' : ['accesskey',
        'class',
        'cols',
        'datafld',
        'datasrc',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'name',
        'readonly',
        'rows',
        'style',
        'tabindex',
        'title',
        'wrap'],
    'tfoot' : ['accesskey',
        'align',
        'char',
        'charoff',
        'class',
        'dir',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable',
        'valign'],
    'th' : ['abbr',
        'accesskey',
        'align',
        'axis',
        'background',
        'bgcolor',
        'bordercolor',
        'bordercolordark',
        'bordercolorlight',
        'char',
        'charoff',
        'class',
        'colspan',
        'dir',
        'headers',
        'height',
        'hidefocus',
        'id',
        'lang',
        'language',
        'nowrap',
        'rowspan',
        'scope',
        'style',
        'tabindex',
        'title',
        'unselectable',
        'valign'],
    'thead' : ['accesskey',
        'align',
        'char',
        'charoff',
        'class',
        'dir',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable',
        'valign'],
    'time' : ['accesskey',
        'class',
        'contenteditable',
        'contextmenu',
        'datetime',
        'dir',
        'draggable',
        'hidden',
        'id',
        'lang',
        'pubdate',
        'spellcheck',
        'style',
        'tabindex',
        'title'],
    'title' : ['dir', 'id', 'lang'],
    'tr' : ['accesskey',
        'align',
        'bgcolor',
        'bordercolor',
        'bordercolordark',
        'bordercolorlight',
        'char',
        'charoff',
        'class',
        'dir',
        'height',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'valign'],
    'tt' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'disabled',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'u' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'ul' : ['accesskey',
        'class',
        'compact',
        'contenteditable',
        'dir',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'type',
        'unselectable'],
    'var' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable'],
    'video' : ['accesskey',
        'autoplay',
        'class',
        'contenteditable',
        'contextmenu',
        'dir',
        'draggable',
        'height',
        'hidden',
        'id',
        'lang',
        'loop',
        'poster',
        'preload',
        'spellcheck',
        'src',
        'style',
        'tabindex',
        'title',
        'width'],
    'wbr' : ['id'],
    'xml' : ['id', 'src'],
    'xmp' : ['accesskey',
        'class',
        'contenteditable',
        'dir',
        'hidefocus',
        'id',
        'lang',
        'language',
        'style',
        'tabindex',
        'title',
        'unselectable']
}

HTML_ATTRIBUTES_VALUES = {
    'abbr' : [],
    'above' : [],
    'accept' : ['*',
        'application/msexcel',
        'application/msword',
        'application/pdf',
        'application/rtf',
        'application/x-zip-compressed',
        'text/html',
        'text/plain'],
    'accept-charset' : ['*', 'ISO-8859-1', 'unknown'],
    'accesskey' : [],
    'action' : [],
    'align' : ['absbottom',
        'absmiddle',
        'baseline',
        'bottom',
        'center',
        'justify',
        'left',
        'middle',
        'right',
        'texttop',
        'top'],
    'alink' : [],
    'allowtransparency' : ['no', 'yes'],
    'alt' : [],
    'application' : ['no', 'yes'],
    'archive' : [],
    'autocomplete' : ['off', 'on'],
    'autofocus' : [],
    'autoplay' : ['false', 'true'],
    'axis' : [],
    'background' : [],
    'balance' : [],
    'behavior' : ['alternate', 'scroll', 'slide'],
    'below' : [],
    'bgcolor' : [],
    'bgproperties' : ['fixed'],
    'border' : [],
    'bordercolor' : [],
    'bordercolordark' : [],
    'bordercolorlight' : [],
    'bottommargin' : [],
    'cellpadding' : [],
    'cellspacing' : [],
    'challenge' : [],
    'char' : [],
    'charoff' : [],
    'charset' : ['*',
        'HZ-GB-2312',
        'ISO-2022-JP',
        'ISO-2022-JP-2',
        'ISO-2022-KR',
        'ISO-8859-1',
        'ISO-8859-10',
        'ISO-8859-15',
        'ISO-8859-2',
        'ISO-8859-3',
        'ISO-8859-4',
        'ISO-8859-5',
        'ISO-8859-6',
        'ISO-8859-7',
        'ISO-8859-8',
        'ISO-8859-9',
        'Shift_JIS',
        'UTF-8',
        'cp1250',
        'cp1251',
        'cp1252',
        'cp1253',
        'cp1254',
        'cp1255',
        'cp1256',
        'cp1257',
        'cp1258',
        'gbk',
        'gb2312'],
    'checked' : ['checked'],
    'cite' : [],
    'class' : [],
    'clear' : ['all', 'left', 'none', 'right'],
    'clip' : [],
    'code' : [],
    'codebase' : [],
    'color' : [],
    'cols' : [],
    'colspan' : [],
    'compact' : ['compact'],
    'content' : ['*',
        'text/html',
        'text/html; charset=HZ-GB-2312',
        'text/html; charset=ISO-2022-JP',
        'text/html; charset=ISO-2022-JP-2',
        'text/html; charset=ISO-2022-KR',
        'text/html; charset=ISO-8859-10',
        'text/html; charset=ISO-8859-15',
        'text/html; charset=ISO-8859-2',
        'text/html; charset=ISO-8859-3',
        'text/html; charset=ISO-8859-4',
        'text/html; charset=ISO-8859-5',
        'text/html; charset=ISO-8859-6',
        'text/html; charset=ISO-8859-7',
        'text/html; charset=ISO-8859-8',
        'text/html; charset=ISO-8859-9',
        'text/html; charset=Shift_JIS',
        'text/html; charset=UTF-8',
        'text/html; charset=cp1250',
        'text/html; charset=cp1251',
        'text/html; charset=cp1252',
        'text/html; charset=cp1253',
        'text/html; charset=cp1254',
        'text/html; charset=cp1255',
        'text/html; charset=cp1256',
        'text/html; charset=cp1257',
        'text/html; charset=cp1258',
        'text/html; charset=iso-8859-1'],
    'contenteditable' : ['false', 'inherit', 'true'],
    'contextmenu' : [],
    'controls' : ['false', 'true'],
    'coords' : [],
    'data' : [],
    'datafld' : [],
    'dataformatas' : ['html', 'text'],
    'datapagesize' : [],
    'datasrc' : [],
    'datetime' : [],
    'declare' : ['declare'],
    'defer' : ['defer'],
    'dir' : ['ltr', 'rtl'],
    'direction' : ['down', 'left', 'right', 'up'],
    'disabled' : ['false', 'true'],
    'draggable' : ['auto', 'false', 'true'],
    'dynsrc' : [],
    'enctype' : ['*',
        'application/x-www-form-urlencoded',
        'multipart/form-data',
        'text/plain'],
    'event' : [],
    'face' : [],
    'for' : [],
    'form' : [],
    'frame' : ['above',
        'below',
        'border',
        'box',
        'hsides',
        'lhs',
        'rhs',
        'void',
        'vsides'],
    'frameborder' : ['0', '1', 'no', 'yes'],
    'framespacing' : [],
    'galleryimg' : ['false', 'no', 'true', 'yes'],
    'headers' : [],
    'height' : [],
    'hidden' : ['false', 'true'],
    'hidefocus' : ['false', 'true'],
    'high' : [],
    'href' : [],
    'hreflang' : [],
    'hspace' : [],
    'http-equiv' : ["Content-Type"],
    'icon' : [],
    'id' : [],
    'keytype' : [],
    'label' : [],
    'lang' : [],
    'language' : ['*',
        'JScript',
        'JavaScript',
        'JavaScript1.1',
        'JavaScript1.2',
        'VBScript',
        'javascript',
        'jscript',
        'php',
        'vbs',
        'vbscript'],
    'left' : [],
    'leftmargin' : [],
    'link' : [],
    'longdesc' : [],
    'loop' : [],
    'low' : [],
    'lowsrc' : [],
    'marginheight' : [],
    'marginwidth' : [],
    'max' : [],
    'maxlength' : [],
    'mayscript' : [],
    'media' : ['*',
        'all',
        'aural',
        'braille',
        'other',
        'print',
        'projection',
        'screen'],
    'method' : ['get', 'post'],
    'methods' : [],
    'min' : [],
    'multiple' : ['multiple'],
    'name' : [],
    'nohref' : ['nohref'],
    'noresize' : ['noresize'],
    'noshade' : ['noshade'],
    'nowrap' : ['nowrap'],
    'object' : [],
    'open' : ['false', 'true'],
    'optimum' : [],
    'overflow' : ['clip', 'none'],
    'pagex' : [],
    'pagey' : [],
    'palette' : ['background', 'foreground'],
    'pluginspage' : [],
    'point-size' : [],
    'poster' : [],
    'preload' : ['auto', 'metadata', 'none'],
    'profile' : [],
    'pubdate' : ['false', 'true'],
    'radiogroup' : [],
    'readonly' : ['readonly'],
    'rel' : ['alternate',
        'bookmark',
        'chapter',
        'contents',
        'copyright',
        'glossary',
        'help',
        'index',
        'next',
        'prev',
        'section',
        'start',
        'stylesheet',
        'subsection'],
    'rev' : ['alternate',
        'bookmark',
        'chapter',
        'contents',
        'copyright',
        'glossary',
        'help',
        'index',
        'next',
        'prev',
        'section',
        'start',
        'stylesheet',
        'subsection'],
    'reversed' : [],
    'rightmargin' : [],
    'rows' : [],
    'rowspan' : [],
    'rules' : ['all', 'cols', 'groups', 'none', 'rows'],
    'scheme' : [],
    'scope' : ['col', 'colgroup', 'row', 'rowgroup'],
    'scroll' : ['auto', 'no', 'yes'],
    'scrollamount' : [],
    'scrolldelay' : [],
    'scrolling' : ['auto', 'no', 'yes'],
    'selected' : ['selected'],
    'shape' : ['circle', 'default', 'poly', 'rect'],
    'size' : ['*', '1', '2', '3', '4', '5', '6', '7'],
    'span' : [],
    'spellcheck' : ['default', 'false', 'true'],
    'src' : [],
    'standby' : [],
    'start' : [],
    'style' : [],
    'summary' : [],
    'tabindex' : [],
    'target' : ['*', '_blank', '_parent', '_self', '_top'],
    'text' : [],
    'title' : [],
    'top' : [],
    'truespeed' : ['truespeed'],
    'type' : ['*',
        '1',
        'A',
        'I',
        'a',
        'application/javascript',
        'application/x-shockwave-flash',
        'button',
        'checkbox',
        'circle',
        'color',
        'date',
        'datetime',
        'datetime-local',
        'disc',
        'email',
        'file',
        'hidden',
        'i',
        'image',
        'month',
        'number',
        'password',
        'radio',
        'range',
        'reset',
        'search',
        'square',
        'submit',
        'tel',
        'text',
        'text/css',
        'text/javascript',
        'text/jscript',
        'text/php',
        'text/tcl',
        'text/vbscript',
        'time',
        'url',
        'week'],
    'units' : ['em', 'px'],
    'unselectable' : ['off', 'on'],
    'urn' : [],
    'usemap' : [],
    'valign' : ['baseline', 'bottom', 'center', 'middle', 'top'],
    'value' : [],
    'valuetype' : ['data', 'object', 'ref'],
    'visibility' : ['hidden', 'inherit', 'shown'],
    'vlink' : [],
    'volume' : [],
    'vspace' : [],
    'weight' : ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    'width' : [],
    'wrap' : ['hard', 'off', 'soft'],
    'xml:space' : ['preserve'],
    'xmlns' : ['http://www.w3.org/1999/xhtml'],
    'z-index' : []
}